src/Entity/Blog.php
<?php

namespace App\Entity;

use App\Repository\BlogRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BlogRepository::class)]
class Blog
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 40)]
    private $title;

    #[ORM\Column(type: 'string', length: 40)]
    private $short_description;

    #[ORM\Column(type: 'text')]
    private $body;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $image;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getShortDescription(): ?string
    {
        return $this->short_description;
    }

    public function setShortDescription(string $short_description): self
    {
        $this->short_description = $short_description;

        return $this;
    }

    public function getBody(): ?string
    {
        return $this->body;
    }

    public function setBody(string $body): self
    {
        $this->body = $body;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

use App\Repository\BlogRepository;

class MainController extends AbstractController
{
    private $blogRepository;
    public function __construct(BlogRepository $blogRepository)
    {
        $this->blogRepository = $blogRepository;
    }

    #[Route('/', name: 'app_main')]
    public function index(): Response
    {
        $blogs = $this->blogRepository->findAll();
        //dd($blogs);
        return $this->render('main/index.html.twig', [
            'blogs' => $blogs,
        ]);
    }
}

templates/main/index.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
	<style>
		.align-center {
			margin: 0 auto;
		}
	</style>
{% endblock %}
{% block body %}

{# <a href="/{{ app.user ? 'logout': 'login' }}" type="button"> {{ app.user ? 'Logout': 'Login' }}
                </a> #}
{% if app.user %}
	<a href="{{path('app_logout')}}">
		Logout
	</a>
{% endif %}

{% if app.user is empty %}
	<a href="{{path('app_login')}}">
		Login
	</a>
{% endif %}

{% if app.user %}
	<p>Welcome
	</p>
	<p>{{ app.user.email }}</p>
</p>{% endif %}<div class="row">
<div class="col-lg-8 align-center">
	<h1>
		Blogs

	</h1>
	{% for blog in blogs %}
		<h4> {{ blog.title }}
		</h4>
		<p> {{ blog.body }}
		</p>

		<tr>
			<td> {{ blog.title }}
			</td>
			<td> {{ blog.shortDescription }}
			</td>
			<td>
				<button class="btn btn-primary">
					Edit
				</button>
			</td>
			<td>
				<button class="btn btn-danger">
					Delete
				</button>
			</td>
		</tr>
	{% endfor %}

</div></div>{% endblock %}